{{- $chartName := include "layer-spec.name" . -}}
{{- $tracingUrl := include "layer-spec.tracingUrl" . -}}
{{- $metricsUrl := include "layer-spec.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DB_HOST: {{ .Values.env.db.host | quote }}
  DB_PORT: {{ .Values.env.db.port | quote }}
  DB_NAME: {{ .Values.env.db.database | quote }}
  DB_SSL_ENABLE: {{ .Values.env.db.sslEnabled | quote }}
  DB_REJECT_UNAUTHORIZED: {{ .Values.env.db.rejectUnauthorized | quote }}
{{- end }}
