global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  imagePullPolicy: Always

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

image:
  repository: layer-spec-registry
  tag: latest

local:
  certs:
    postgres:
      ca: "certs/postgres/rootCA.crt"
      key: "certs/postgres/avi.key"
      cert: "certs/postgres/avi.crt"

postgresSecret:
  enabled: true
  useExternal: false
  externalSecretName:
  userName: postgres
  password: postgres

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  db:
    host: localhost
    database: sync-storage
    port: 5432
    sslEnabled: false
    rejectUnauthorized: true
  
resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: false
  path: /

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
